---
title: Python Basics Blog
author: Allee Ramirez
date: '2019-12-18'
slug: python-basics-blog
categories: []
tags: []
description: ''
---

##1. Variables
In Python it is really easy to define a variable and set a value to it. 

ex)two = 2
some_number = 10000

##2. Control Flow: conditional statements
“If” uses an expression to evaluate to True or False. If it is True, it executes what it is inside the if statement. 

ex)if True:
  print("Hello Python If")

if 2 > 1:
  print("2 is greater than 1")
  
The “else” statement will be executed if “if” expression is false  

ex)if 1 > 2:
  print("1 is greater than 2")
else:
  print("1 is not greater than 2")

##3. Looping / Iterator
In Python we can iterate in different forms. I’ll talk about 2: while and for.
While Looping: while the statement is True, the code inside the block will be executed. So this code will print the number from 1 to 10.

ex) num = 1

while num <= 10:
    print(num)
    num += 1 

For Looping: you pass the variable “num” to the block and the “for” statement will iterate it for you. This code will print the same as “while” code: from 1 to 10.

ex) for i in range(1, 11):
  print(i)


